import { createParamDecorator } from '@nestjs/common';
import { Request } from 'express';

/**
 * Cognitor user decorator. It will return decoed token generated by AWS Cognito.
 */
export const CognitoUser = createParamDecorator(
  (data: string, req: Request) => {
    // tslint:disable-next-line
    return req['decoded'];
  },
);
